# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.connectors_update_by_id_request_connector_configuration import ConnectorsUpdateByIdRequestConnectorConfiguration

class RequiredConnectorsUpdateByIdRequestConnector(TypedDict):
    name: str

    connector_type: str

    configuration: ConnectorsUpdateByIdRequestConnectorConfiguration

    connector_name: str

class OptionalConnectorsUpdateByIdRequestConnector(TypedDict, total=False):
    pass

class ConnectorsUpdateByIdRequestConnector(RequiredConnectorsUpdateByIdRequestConnector, OptionalConnectorsUpdateByIdRequestConnector):
    pass
