# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.connector_definitions_get_by_name_response_connector_spec import ConnectorDefinitionsGetByNameResponseConnectorSpec
from multiwoven_python_sdk.type.connector_definitions_get_by_name_response_tags import ConnectorDefinitionsGetByNameResponseTags

class RequiredConnectorDefinitionsGetByNameResponse(TypedDict):
    pass

class OptionalConnectorDefinitionsGetByNameResponse(TypedDict, total=False):
    tags: ConnectorDefinitionsGetByNameResponseTags

    name: str

    connector_type: str

    connector_subtype: str

    documentation_url: str

    github_issue_label: str

    icon: str

    license: str

    release_stage: str

    support_level: str

    connector_spec: ConnectorDefinitionsGetByNameResponseConnectorSpec

class ConnectorDefinitionsGetByNameResponse(RequiredConnectorDefinitionsGetByNameResponse, OptionalConnectorDefinitionsGetByNameResponse):
    pass
