# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.connector_definitions_check_connection_request_connection_spec import ConnectorDefinitionsCheckConnectionRequestConnectionSpec

class RequiredConnectorDefinitionsCheckConnectionRequest(TypedDict):
    pass

class OptionalConnectorDefinitionsCheckConnectionRequest(TypedDict, total=False):
    type: str

    name: str

    connection_spec: ConnectorDefinitionsCheckConnectionRequestConnectionSpec

class ConnectorDefinitionsCheckConnectionRequest(RequiredConnectorDefinitionsCheckConnectionRequest, OptionalConnectorDefinitionsCheckConnectionRequest):
    pass
