# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.connectors_update_by_id_response_data_attributes_configuration import ConnectorsUpdateByIdResponseDataAttributesConfiguration

class RequiredConnectorsUpdateByIdResponseDataAttributes(TypedDict):
    pass

class OptionalConnectorsUpdateByIdResponseDataAttributes(TypedDict, total=False):
    name: str

    connector_type: str

    workspace_id: int

    created_at: datetime

    updated_at: datetime

    configuration: ConnectorsUpdateByIdResponseDataAttributesConfiguration

    connector_name: str

    icon: str

class ConnectorsUpdateByIdResponseDataAttributes(RequiredConnectorsUpdateByIdResponseDataAttributes, OptionalConnectorsUpdateByIdResponseDataAttributes):
    pass
