# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.connector_definitions_get_based_on_type_response_item_connector_spec import ConnectorDefinitionsGetBasedOnTypeResponseItemConnectorSpec
from multiwoven_python_sdk.type.connector_definitions_get_based_on_type_response_item_tags import ConnectorDefinitionsGetBasedOnTypeResponseItemTags

class RequiredConnectorDefinitionsGetBasedOnTypeResponseItem(TypedDict):
    pass

class OptionalConnectorDefinitionsGetBasedOnTypeResponseItem(TypedDict, total=False):
    tags: ConnectorDefinitionsGetBasedOnTypeResponseItemTags

    name: str

    connector_type: str

    connector_subtype: str

    documentation_url: str

    github_issue_label: str

    icon: str

    license: str

    release_stage: str

    support_level: str

    connector_spec: ConnectorDefinitionsGetBasedOnTypeResponseItemConnectorSpec

class ConnectorDefinitionsGetBasedOnTypeResponseItem(RequiredConnectorDefinitionsGetBasedOnTypeResponseItem, OptionalConnectorDefinitionsGetBasedOnTypeResponseItem):
    pass
