# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.connectors_create_new_connector_request_connector import ConnectorsCreateNewConnectorRequestConnector

class RequiredConnectorsCreateNewConnectorRequest(TypedDict):
    pass

class OptionalConnectorsCreateNewConnectorRequest(TypedDict, total=False):
    connector: ConnectorsCreateNewConnectorRequestConnector

class ConnectorsCreateNewConnectorRequest(RequiredConnectorsCreateNewConnectorRequest, OptionalConnectorsCreateNewConnectorRequest):
    pass
