# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.models_list_all_models_response_data_item_attributes import ModelsListAllModelsResponseDataItemAttributes

class RequiredModelsListAllModelsResponseDataItem(TypedDict):
    pass

class OptionalModelsListAllModelsResponseDataItem(TypedDict, total=False):
    id: str

    type: str

    attributes: ModelsListAllModelsResponseDataItemAttributes

class ModelsListAllModelsResponseDataItem(RequiredModelsListAllModelsResponseDataItem, OptionalModelsListAllModelsResponseDataItem):
    pass
