# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.models_list_all_models_response_data import ModelsListAllModelsResponseData
from multiwoven_python_sdk.type.models_list_all_models_response_links import ModelsListAllModelsResponseLinks

class RequiredModelsListAllModelsResponse(TypedDict):
    pass

class OptionalModelsListAllModelsResponse(TypedDict, total=False):
    data: ModelsListAllModelsResponseData

    links: ModelsListAllModelsResponseLinks

class ModelsListAllModelsResponse(RequiredModelsListAllModelsResponse, OptionalModelsListAllModelsResponse):
    pass
