# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredModelsUpdateModelByIdRequestModel(TypedDict):
    name: str

    query: str

    query_type: str

    connector_id: int

class OptionalModelsUpdateModelByIdRequestModel(TypedDict, total=False):
    description: str

    primary_key: str

class ModelsUpdateModelByIdRequestModel(RequiredModelsUpdateModelByIdRequestModel, OptionalModelsUpdateModelByIdRequestModel):
    pass
