# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.syncs_update_specific_sync_response_data import SyncsUpdateSpecificSyncResponseData

class RequiredSyncsUpdateSpecificSyncResponse(TypedDict):
    pass

class OptionalSyncsUpdateSpecificSyncResponse(TypedDict, total=False):
    success: bool

    message: str

    data: SyncsUpdateSpecificSyncResponseData

class SyncsUpdateSpecificSyncResponse(RequiredSyncsUpdateSpecificSyncResponse, OptionalSyncsUpdateSpecificSyncResponse):
    pass
