# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSyncRecordsListForSyncRunResponseDataItemAttributesRecord(TypedDict):
    pass

class OptionalSyncRecordsListForSyncRunResponseDataItemAttributesRecord(TypedDict, total=False):
    id: int

    state: str

    last_name: str

    first_name: str

    phone_number: int

    email_address: str

class SyncRecordsListForSyncRunResponseDataItemAttributesRecord(RequiredSyncRecordsListForSyncRunResponseDataItemAttributesRecord, OptionalSyncRecordsListForSyncRunResponseDataItemAttributesRecord):
    pass
