# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSyncRunsListBySyncIdResponseDataItemAttributes(TypedDict):
    pass

class OptionalSyncRunsListBySyncIdResponseDataItemAttributes(TypedDict, total=False):
    sync_id: int

    status: str

    started_at: datetime

    finished_at: datetime

    duration: typing.Union[int, float]

    total_query_rows: int

    total_rows: int

    successful_rows: int

    failed_rows: int

    error: typing.Optional[str]

    created_at: datetime

    updated_at: datetime

class SyncRunsListBySyncIdResponseDataItemAttributes(RequiredSyncRunsListBySyncIdResponseDataItemAttributes, OptionalSyncRunsListBySyncIdResponseDataItemAttributes):
    pass
