# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSyncRecordsListForSyncRun404Response(TypedDict):
    pass

class OptionalSyncRecordsListForSyncRun404Response(TypedDict, total=False):
    message: str

    status: str

class SyncRecordsListForSyncRun404Response(RequiredSyncRecordsListForSyncRun404Response, OptionalSyncRecordsListForSyncRun404Response):
    pass
