# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean(TypedDict):
    pass

class OptionalSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean(TypedDict, total=False):
    # Description of the boolean field.
    description: str

    # Data type for boolean field.
    type: str

class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean(RequiredSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean, OptionalSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean):
    pass
