# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.syncs_create_new_sync_operation_response_attributes import SyncsCreateNewSyncOperationResponseAttributes

class RequiredSyncsCreateNewSyncOperationResponse(TypedDict):
    pass

class OptionalSyncsCreateNewSyncOperationResponse(TypedDict, total=False):
    id: str

    type: str

    attributes: SyncsCreateNewSyncOperationResponseAttributes

class SyncsCreateNewSyncOperationResponse(RequiredSyncsCreateNewSyncOperationResponse, OptionalSyncsCreateNewSyncOperationResponse):
    pass
