# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast(TypedDict):
    pass

class OptionalSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast(TypedDict, total=False):
    # Description of the cast filter.
    description: str

    # Expression to cast value to specified type.
    value: str

class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast(RequiredSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast, OptionalSyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast):
    pass
