# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.syncs_list_operations_response_data_item_attributes_configuration import SyncsListOperationsResponseDataItemAttributesConfiguration

class RequiredSyncsListOperationsResponseDataItemAttributes(TypedDict):
    pass

class OptionalSyncsListOperationsResponseDataItemAttributes(TypedDict, total=False):
    source_id: int

    destination_id: int

    model_id: int

    configuration: SyncsListOperationsResponseDataItemAttributesConfiguration

    schedule_type: str

    sync_mode: str

    sync_interval: int

    sync_interval_unit: str

    stream_name: str

    status: str

class SyncsListOperationsResponseDataItemAttributes(RequiredSyncsListOperationsResponseDataItemAttributes, OptionalSyncsListOperationsResponseDataItemAttributes):
    pass
