# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from multiwoven_python_sdk.type.syncs_show_details_response_attributes_configuration import SyncsShowDetailsResponseAttributesConfiguration

class RequiredSyncsShowDetailsResponseAttributes(TypedDict):
    pass

class OptionalSyncsShowDetailsResponseAttributes(TypedDict, total=False):
    source_id: int

    destination_id: int

    model_id: int

    configuration: SyncsShowDetailsResponseAttributesConfiguration

    schedule_type: str

    sync_mode: str

    sync_interval: int

    sync_interval_unit: str

    stream_name: str

    status: str

class SyncsShowDetailsResponseAttributes(RequiredSyncsShowDetailsResponseAttributes, OptionalSyncsShowDetailsResponseAttributes):
    pass
