# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from multiwoven_python_sdk import schemas  # noqa: F401


class ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreams(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    Array of stream objects, varying based on connector ID.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItem']:
            return ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItem'], typing.List['ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreams':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItem':
        return super().__getitem__(i)

from multiwoven_python_sdk.model.connectors_discover_catalog_info_response_data_attributes_catalog_streams_item import ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItem
