# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from multiwoven_python_sdk import schemas  # noqa: F401


class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Details for variables within template mapping.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def current_timestamp() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp
            __annotations__ = {
                "current_timestamp": current_timestamp,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["current_timestamp"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["current_timestamp", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["current_timestamp"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["current_timestamp", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        current_timestamp: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable':
        return super().__new__(
            cls,
            *args,
            current_timestamp=current_timestamp,
            _configuration=_configuration,
            **kwargs,
        )

from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_template_variable_current_timestamp import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariableCurrentTimestamp
