# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from multiwoven_python_sdk import schemas  # noqa: F401


class SyncRunsListBySyncIdResponseData(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['SyncRunsListBySyncIdResponseDataItem']:
            return SyncRunsListBySyncIdResponseDataItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['SyncRunsListBySyncIdResponseDataItem'], typing.List['SyncRunsListBySyncIdResponseDataItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'SyncRunsListBySyncIdResponseData':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'SyncRunsListBySyncIdResponseDataItem':
        return super().__getitem__(i)

from multiwoven_python_sdk.model.sync_runs_list_by_sync_id_response_data_item import SyncRunsListBySyncIdResponseDataItem
