# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from multiwoven_python_sdk import schemas  # noqa: F401


class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Details for static mapping type.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def string() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString
        
            @staticmethod
            def number() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber
        
            @staticmethod
            def boolean() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean
        
            @staticmethod
            def null() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull
            __annotations__ = {
                "string": string,
                "number": number,
                "boolean": boolean,
                "null": null,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["string"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["number"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["boolean"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["null"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["string", "number", "boolean", "null", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["string"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["number"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["boolean"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["null"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["string", "number", "boolean", "null", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        string: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString', schemas.Unset] = schemas.unset,
        number: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber', schemas.Unset] = schemas.unset,
        boolean: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean', schemas.Unset] = schemas.unset,
        null: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic':
        return super().__new__(
            cls,
            *args,
            string=string,
            number=number,
            boolean=boolean,
            null=null,
            _configuration=_configuration,
            **kwargs,
        )

from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_static_boolean import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean
from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_static_null import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull
from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_static_number import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber
from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_static_string import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString
