# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from multiwoven_python_sdk import schemas  # noqa: F401


class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Details for template mapping type.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def variable() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable
        
            @staticmethod
            def filter() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter
            __annotations__ = {
                "variable": variable,
                "filter": filter,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["variable"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["filter"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["variable", "filter", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["variable"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["filter"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["variable", "filter", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        variable: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable', schemas.Unset] = schemas.unset,
        filter: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplate':
        return super().__new__(
            cls,
            *args,
            variable=variable,
            filter=filter,
            _configuration=_configuration,
            **kwargs,
        )

from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_template_filter import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter
from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_template_variable import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateVariable
