# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from multiwoven_python_sdk import schemas  # noqa: F401


class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Details for filters within template mapping.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def cast() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast
        
            @staticmethod
            def regex_replace() -> typing.Type['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace']:
                return SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace
            __annotations__ = {
                "cast": cast,
                "regex_replace": regex_replace,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cast"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["regex_replace"]) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["cast", "regex_replace", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cast"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["regex_replace"]) -> typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["cast", "regex_replace", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cast: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast', schemas.Unset] = schemas.unset,
        regex_replace: typing.Union['SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilter':
        return super().__new__(
            cls,
            *args,
            cast=cast,
            regex_replace=regex_replace,
            _configuration=_configuration,
            **kwargs,
        )

from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_template_filter_cast import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterCast
from multiwoven_python_sdk.model.syncs_get_report_data_response_data_configurations_catalog_mapping_types_template_filter_regex_replace import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesTemplateFilterRegexReplace
