# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import multiwoven_python_sdk
from multiwoven_python_sdk.model.models_list_all_models_response_data_item_attributes import ModelsListAllModelsResponseDataItemAttributes
from multiwoven_python_sdk import configuration


class TestModelsListAllModelsResponseDataItemAttributes(unittest.TestCase):
    """ModelsListAllModelsResponseDataItemAttributes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
