# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import multiwoven_python_sdk
from multiwoven_python_sdk.model.connectors_update_by_id_response import ConnectorsUpdateByIdResponse
from multiwoven_python_sdk import configuration


class TestConnectorsUpdateByIdResponse(unittest.TestCase):
    """ConnectorsUpdateByIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
