# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import multiwoven_python_sdk
from multiwoven_python_sdk.paths.api_v1_models_id import delete
from multiwoven_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiV1ModelsId(ApiTestMixin, unittest.TestCase):
    """
    ApiV1ModelsId unit test stubs
        Deletes a model
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
