# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from multiwoven_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from multiwoven_python_sdk.api_response import AsyncGeneratorResponse
from multiwoven_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from multiwoven_python_sdk import schemas  # noqa: F401

from multiwoven_python_sdk.model.sync_records_list_for_sync_run404_response import SyncRecordsListForSyncRun404Response as SyncRecordsListForSyncRun404ResponseSchema
from multiwoven_python_sdk.model.sync_records_list_for_sync_run_response import SyncRecordsListForSyncRunResponse as SyncRecordsListForSyncRunResponseSchema

from multiwoven_python_sdk.type.sync_records_list_for_sync_run404_response import SyncRecordsListForSyncRun404Response
from multiwoven_python_sdk.type.sync_records_list_for_sync_run_response import SyncRecordsListForSyncRunResponse

from ...api_client import Dictionary
from multiwoven_python_sdk.pydantic.sync_records_list_for_sync_run404_response import SyncRecordsListForSyncRun404Response as SyncRecordsListForSyncRun404ResponsePydantic
from multiwoven_python_sdk.pydantic.sync_records_list_for_sync_run_response import SyncRecordsListForSyncRunResponse as SyncRecordsListForSyncRunResponsePydantic

from . import path

# Query params
StatusSchema = schemas.StrSchema
PageSchema = schemas.IntSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'status': typing.Union[StatusSchema, str, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_status = api_client.QueryParameter(
    name="status",
    style=api_client.ParameterStyle.FORM,
    schema=StatusSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
# Path params
SyncIdSchema = schemas.IntSchema
SyncRunIdSchema = schemas.IntSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'sync_id': typing.Union[SyncIdSchema, decimal.Decimal, int, ],
        'sync_run_id': typing.Union[SyncRunIdSchema, decimal.Decimal, int, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_sync_id = api_client.PathParameter(
    name="sync_id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=SyncIdSchema,
    required=True,
)
request_path_sync_run_id = api_client.PathParameter(
    name="sync_run_id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=SyncRunIdSchema,
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = SyncRecordsListForSyncRunResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: SyncRecordsListForSyncRunResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: SyncRecordsListForSyncRunResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = SyncRecordsListForSyncRun404ResponseSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: SyncRecordsListForSyncRun404Response


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: SyncRecordsListForSyncRun404Response


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '404': _response_for_404,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _list_for_sync_run_mapped_args(
        self,
        sync_id: int,
        sync_run_id: int,
        status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _path_params = {}
        if status is not None:
            _query_params["status"] = status
        if page is not None:
            _query_params["page"] = page
        if sync_id is not None:
            _path_params["sync_id"] = sync_id
        if sync_run_id is not None:
            _path_params["sync_run_id"] = sync_run_id
        args.query = _query_params
        args.path = _path_params
        return args

    async def _alist_for_sync_run_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        List sync records for a specific sync run
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_sync_id,
            request_path_sync_run_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_status,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/v1/syncs/{sync_id}/sync_runs/{sync_run_id}/sync_records',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _list_for_sync_run_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        List sync records for a specific sync run
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_sync_id,
            request_path_sync_run_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_status,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/v1/syncs/{sync_id}/sync_runs/{sync_run_id}/sync_records',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ListForSyncRunRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def alist_for_sync_run(
        self,
        sync_id: int,
        sync_run_id: int,
        status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_for_sync_run_mapped_args(
            sync_id=sync_id,
            sync_run_id=sync_run_id,
            status=status,
            page=page,
        )
        return await self._alist_for_sync_run_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def list_for_sync_run(
        self,
        sync_id: int,
        sync_run_id: int,
        status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_for_sync_run_mapped_args(
            sync_id=sync_id,
            sync_run_id=sync_run_id,
            status=status,
            page=page,
        )
        return self._list_for_sync_run_oapg(
            query_params=args.query,
            path_params=args.path,
        )

class ListForSyncRun(BaseApi):

    async def alist_for_sync_run(
        self,
        sync_id: int,
        sync_run_id: int,
        status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> SyncRecordsListForSyncRunResponsePydantic:
        raw_response = await self.raw.alist_for_sync_run(
            sync_id=sync_id,
            sync_run_id=sync_run_id,
            status=status,
            page=page,
            **kwargs,
        )
        if validate:
            return SyncRecordsListForSyncRunResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(SyncRecordsListForSyncRunResponsePydantic, raw_response.body)
    
    
    def list_for_sync_run(
        self,
        sync_id: int,
        sync_run_id: int,
        status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        validate: bool = False,
    ) -> SyncRecordsListForSyncRunResponsePydantic:
        raw_response = self.raw.list_for_sync_run(
            sync_id=sync_id,
            sync_run_id=sync_run_id,
            status=status,
            page=page,
        )
        if validate:
            return SyncRecordsListForSyncRunResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(SyncRecordsListForSyncRunResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        sync_id: int,
        sync_run_id: int,
        status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_for_sync_run_mapped_args(
            sync_id=sync_id,
            sync_run_id=sync_run_id,
            status=status,
            page=page,
        )
        return await self._alist_for_sync_run_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        sync_id: int,
        sync_run_id: int,
        status: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_for_sync_run_mapped_args(
            sync_id=sync_id,
            sync_run_id=sync_run_id,
            status=status,
            page=page,
        )
        return self._list_for_sync_run_oapg(
            query_params=args.query,
            path_params=args.path,
        )

