# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from multiwoven_python_sdk.paths.api_v1_connector_definitions_check_connection.post import CheckConnection
from multiwoven_python_sdk.paths.api_v1_connector_definitions.get import GetBasedOnType
from multiwoven_python_sdk.paths.api_v1_connector_definitions_connector_name.get import GetByName
from multiwoven_python_sdk.apis.tags.connector_definitions_api_raw import ConnectorDefinitionsApiRaw


class ConnectorDefinitionsApi(
    CheckConnection,
    GetBasedOnType,
    GetByName,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ConnectorDefinitionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ConnectorDefinitionsApiRaw(api_client)
