# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from multiwoven_python_sdk.paths.api_v1_connectors.post import CreateNewConnector
from multiwoven_python_sdk.paths.api_v1_connectors_id.delete import DeleteById
from multiwoven_python_sdk.paths.api_v1_connectors_id_discover.get import DiscoverCatalogInfo
from multiwoven_python_sdk.paths.api_v1_connectors_id.get import GetById
from multiwoven_python_sdk.paths.api_v1_connectors.get import ListAll
from multiwoven_python_sdk.paths.api_v1_connectors_id_query_source.post import QuerySource
from multiwoven_python_sdk.paths.api_v1_connectors_id.put import UpdateById
from multiwoven_python_sdk.apis.tags.connectors_api_raw import ConnectorsApiRaw


class ConnectorsApi(
    CreateNewConnector,
    DeleteById,
    DiscoverCatalogInfo,
    GetById,
    ListAll,
    QuerySource,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ConnectorsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ConnectorsApiRaw(api_client)
