# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from multiwoven_python_sdk.paths.api_v1_connectors.post import CreateNewConnectorRaw
from multiwoven_python_sdk.paths.api_v1_connectors_id.delete import DeleteByIdRaw
from multiwoven_python_sdk.paths.api_v1_connectors_id_discover.get import DiscoverCatalogInfoRaw
from multiwoven_python_sdk.paths.api_v1_connectors_id.get import GetByIdRaw
from multiwoven_python_sdk.paths.api_v1_connectors.get import ListAllRaw
from multiwoven_python_sdk.paths.api_v1_connectors_id_query_source.post import QuerySourceRaw
from multiwoven_python_sdk.paths.api_v1_connectors_id.put import UpdateByIdRaw


class ConnectorsApiRaw(
    CreateNewConnectorRaw,
    DeleteByIdRaw,
    DiscoverCatalogInfoRaw,
    GetByIdRaw,
    ListAllRaw,
    QuerySourceRaw,
    UpdateByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
