# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from multiwoven_python_sdk.paths.api_v1_connector_definitions_check_connection.post import CheckConnectionRaw
from multiwoven_python_sdk.paths.api_v1_connector_definitions.get import GetBasedOnTypeRaw
from multiwoven_python_sdk.paths.api_v1_connector_definitions_connector_name.get import GetByNameRaw


class ConnectorDefinitionsApiRaw(
    CheckConnectionRaw,
    GetBasedOnTypeRaw,
    GetByNameRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
