# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from multiwoven_python_sdk.paths.api_v1_models.post import CreateModelRaw
from multiwoven_python_sdk.paths.api_v1_models_id.delete import DeleteModelRaw
from multiwoven_python_sdk.paths.api_v1_models_id.get import GetByIdRaw
from multiwoven_python_sdk.paths.api_v1_models.get import ListAllModelsRaw
from multiwoven_python_sdk.paths.api_v1_models_id.put import UpdateModelByIdRaw


class ModelsApiRaw(
    CreateModelRaw,
    DeleteModelRaw,
    GetByIdRaw,
    ListAllModelsRaw,
    UpdateModelByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
