# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from multiwoven_python_sdk.paths.api_v1_models.post import CreateModel
from multiwoven_python_sdk.paths.api_v1_models_id.delete import DeleteModel
from multiwoven_python_sdk.paths.api_v1_models_id.get import GetById
from multiwoven_python_sdk.paths.api_v1_models.get import ListAllModels
from multiwoven_python_sdk.paths.api_v1_models_id.put import UpdateModelById
from multiwoven_python_sdk.apis.tags.models_api_raw import ModelsApiRaw


class ModelsApi(
    CreateModel,
    DeleteModel,
    GetById,
    ListAllModels,
    UpdateModelById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ModelsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ModelsApiRaw(api_client)
