# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from multiwoven_python_sdk.paths.api_v1_reports.get import GetDataBasedOnTypeRaw


class ReportsApiRaw(
    GetDataBasedOnTypeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
