# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from multiwoven_python_sdk.paths.api_v1_syncs.post import CreateNewSyncOperationRaw
from multiwoven_python_sdk.paths.api_v1_syncs_id.delete import DeleteSyncOperationRaw
from multiwoven_python_sdk.paths.api_v1_syncs_configurations.get import GetReportDataRaw
from multiwoven_python_sdk.paths.api_v1_syncs.get import ListOperationsRaw
from multiwoven_python_sdk.paths.api_v1_syncs_id.get import ShowDetailsRaw
from multiwoven_python_sdk.paths.api_v1_syncs_id.put import UpdateSpecificSyncRaw


class SyncsApiRaw(
    CreateNewSyncOperationRaw,
    DeleteSyncOperationRaw,
    GetReportDataRaw,
    ListOperationsRaw,
    ShowDetailsRaw,
    UpdateSpecificSyncRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
