# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.connector_definitions_get_based_on_type_response_item_connector_spec_connection_specification import ConnectorDefinitionsGetBasedOnTypeResponseItemConnectorSpecConnectionSpecification

class ConnectorDefinitionsGetBasedOnTypeResponseItemConnectorSpec(BaseModel):
    documentation_url: typing.Optional[str] = Field(None, alias='documentation_url')

    connection_specification: typing.Optional[ConnectorDefinitionsGetBasedOnTypeResponseItemConnectorSpecConnectionSpecification] = Field(None, alias='connection_specification')
    class Config:
        arbitrary_types_allowed = True
