# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.connector_definitions_get_by_name_response_connector_spec_connection_specification import ConnectorDefinitionsGetByNameResponseConnectorSpecConnectionSpecification

class ConnectorDefinitionsGetByNameResponseConnectorSpec(BaseModel):
    documentation_url: typing.Optional[str] = Field(None, alias='documentation_url')

    connection_specification: typing.Optional[ConnectorDefinitionsGetByNameResponseConnectorSpecConnectionSpecification] = Field(None, alias='connection_specification')

    supports_normalization: typing.Optional[bool] = Field(None, alias='supports_normalization')

    supports_dbt: typing.Optional[bool] = Field(None, alias='supports_dbt')

    stream_type: typing.Optional[str] = Field(None, alias='stream_type')
    class Config:
        arbitrary_types_allowed = True
