# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ConnectorDefinitionsCheckConnectionResponse(BaseModel):
    result: typing.Optional[Literal["success", "failure"]] = Field(None, alias='result')

    details: typing.Optional[str] = Field(None, alias='details')
    class Config:
        arbitrary_types_allowed = True
