# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.connectors_discover_catalog_info_response_data_attributes_catalog_streams_item_json_schema import ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItemJsonSchema

class ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItem(BaseModel):
    name: typing.Optional[str] = Field(None, alias='name')

    action: typing.Optional[str] = Field(None, alias='action')

    json_schema: typing.Optional[ConnectorsDiscoverCatalogInfoResponseDataAttributesCatalogStreamsItemJsonSchema] = Field(None, alias='json_schema')

    url: typing.Optional[str] = Field(None, alias='url')

    request_method: typing.Optional[str] = Field(None, alias='request_method')
    class Config:
        arbitrary_types_allowed = True
