# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.connectors_create_new_connector_response_data_attributes_configuration import ConnectorsCreateNewConnectorResponseDataAttributesConfiguration

class ConnectorsCreateNewConnectorResponseDataAttributes(BaseModel):
    name: typing.Optional[str] = Field(None, alias='name')

    connector_type: typing.Optional[str] = Field(None, alias='connector_type')

    workspace_id: typing.Optional[int] = Field(None, alias='workspace_id')

    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    updated_at: typing.Optional[datetime] = Field(None, alias='updated_at')

    configuration: typing.Optional[ConnectorsCreateNewConnectorResponseDataAttributesConfiguration] = Field(None, alias='configuration')

    connector_name: typing.Optional[str] = Field(None, alias='connector_name')

    icon: typing.Optional[str] = Field(None, alias='icon')
    class Config:
        arbitrary_types_allowed = True
