# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ModelsCreateModelResponseDataAttributes(BaseModel):
    description: typing.Optional[str] = Field(None, alias='description')

    name: typing.Optional[str] = Field(None, alias='name')

    query: typing.Optional[str] = Field(None, alias='query')

    query_type: typing.Optional[str] = Field(None, alias='query_type')

    primary_key: typing.Optional[str] = Field(None, alias='primary_key')

    connector_id: typing.Optional[int] = Field(None, alias='connector_id')

    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    updated_at: typing.Optional[datetime] = Field(None, alias='updated_at')
    class Config:
        arbitrary_types_allowed = True
