# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.sync_records_list_for_sync_run_response_data_item_attributes import SyncRecordsListForSyncRunResponseDataItemAttributes

class SyncRecordsListForSyncRunResponseDataItem(BaseModel):
    id: typing.Optional[str] = Field(None, alias='id')

    type: typing.Optional[str] = Field(None, alias='type')

    attributes: typing.Optional[SyncRecordsListForSyncRunResponseDataItemAttributes] = Field(None, alias='attributes')
    class Config:
        arbitrary_types_allowed = True
