# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.syncs_list_operations_response_data import SyncsListOperationsResponseData
from multiwoven_python_sdk.pydantic.syncs_list_operations_response_links import SyncsListOperationsResponseLinks

class SyncsListOperationsResponse(BaseModel):
    data: SyncsListOperationsResponseData = Field(alias='data')

    links: SyncsListOperationsResponseLinks = Field(alias='links')
    class Config:
        arbitrary_types_allowed = True
