# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.syncs_get_report_data_response_data_configurations_catalog_mapping_types_static_boolean import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean
from multiwoven_python_sdk.pydantic.syncs_get_report_data_response_data_configurations_catalog_mapping_types_static_null import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull
from multiwoven_python_sdk.pydantic.syncs_get_report_data_response_data_configurations_catalog_mapping_types_static_number import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber
from multiwoven_python_sdk.pydantic.syncs_get_report_data_response_data_configurations_catalog_mapping_types_static_string import SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString

class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStatic(BaseModel):
    string: typing.Optional[SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticString] = Field(None, alias='string')

    number: typing.Optional[SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNumber] = Field(None, alias='number')

    boolean: typing.Optional[SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean] = Field(None, alias='boolean')

    null: typing.Optional[SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticNull] = Field(None, alias='null')
    class Config:
        arbitrary_types_allowed = True
