# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.syncs_create_new_sync_operation_request_sync_configuration import SyncsCreateNewSyncOperationRequestSyncConfiguration

class SyncsCreateNewSyncOperationRequestSync(BaseModel):
    source_id: int = Field(alias='source_id')

    destination_id: int = Field(alias='destination_id')

    model_id_: int = Field(alias='model_id')

    schedule_type: Literal["automated"] = Field(alias='schedule_type')

    configuration: SyncsCreateNewSyncOperationRequestSyncConfiguration = Field(alias='configuration')

    stream_name: str = Field(alias='stream_name')

    sync_mode: Literal["full_refresh"] = Field(alias='sync_mode')

    sync_interval: int = Field(alias='sync_interval')

    sync_interval_unit: Literal["minutes"] = Field(alias='sync_interval_unit')
    class Config:
        arbitrary_types_allowed = True
