# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class SyncsGetReportDataResponseDataConfigurationsCatalogMappingTypesStaticBoolean(BaseModel):
    # Description of the boolean field.
    description: typing.Optional[str] = Field(None, alias='description')

    # Data type for boolean field.
    type: typing.Optional[Literal["boolean"]] = Field(None, alias='type')
    class Config:
        arbitrary_types_allowed = True
