# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from multiwoven_python_sdk.pydantic.sync_records_list_for_sync_run_response_data_item_attributes_record import SyncRecordsListForSyncRunResponseDataItemAttributesRecord

class SyncRecordsListForSyncRunResponseDataItemAttributes(BaseModel):
    sync_id: typing.Optional[int] = Field(None, alias='sync_id')

    sync_run_id: typing.Optional[int] = Field(None, alias='sync_run_id')

    record: typing.Optional[SyncRecordsListForSyncRunResponseDataItemAttributesRecord] = Field(None, alias='record')

    status: typing.Optional[str] = Field(None, alias='status')

    action: typing.Optional[str] = Field(None, alias='action')

    error: typing.Optional[typing.Optional[str]] = Field(None, alias='error')

    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    updated_at: typing.Optional[datetime] = Field(None, alias='updated_at')
    class Config:
        arbitrary_types_allowed = True
