# coding: utf-8

"""
    MultiWoven API

    Open-source Reverse ETL that makes data segmentation, sync and activation both easy and fully secure.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from multiwoven_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from multiwoven_python_sdk.api_response import AsyncGeneratorResponse
from multiwoven_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from multiwoven_python_sdk import schemas  # noqa: F401

from multiwoven_python_sdk.model.reports_get_data_based_on_type_response import ReportsGetDataBasedOnTypeResponse as ReportsGetDataBasedOnTypeResponseSchema

from multiwoven_python_sdk.type.reports_get_data_based_on_type_response import ReportsGetDataBasedOnTypeResponse

from ...api_client import Dictionary
from multiwoven_python_sdk.pydantic.reports_get_data_based_on_type_response import ReportsGetDataBasedOnTypeResponse as ReportsGetDataBasedOnTypeResponsePydantic

# Query params


class TypeSchema(
    schemas.EnumBase,
    schemas.StrSchema
):
    
    @schemas.classproperty
    def WORKSPACE_ACTIVITY(cls):
        return cls("workspace_activity")


class MetricSchema(
    schemas.EnumBase,
    schemas.StrSchema
):
    
    @schemas.classproperty
    def SYNC_RUN_TRIGGERED(cls):
        return cls("sync_run_triggered")
    
    @schemas.classproperty
    def TOTAL_SYNC_RUN_ROWS(cls):
        return cls("total_sync_run_rows")
    
    @schemas.classproperty
    def ALL(cls):
        return cls("all")


class ConnectorIdsSchema(
    schemas.ListSchema
):


    class MetaOapg:
        items = schemas.IntSchema

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ConnectorIdsSchema':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> MetaOapg.items:
        return super().__getitem__(i)


class TimePeriodSchema(
    schemas.EnumBase,
    schemas.StrSchema
):
    
    @schemas.classproperty
    def WEEK(cls):
        return cls("one_week")
    
    @schemas.classproperty
    def DAY(cls):
        return cls("one_day")
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
        'type': typing.Union[TypeSchema, str, ],
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'metric': typing.Union[MetricSchema, str, ],
        'connector_ids': typing.Union[ConnectorIdsSchema, list, tuple, ],
        'time_period': typing.Union[TimePeriodSchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_type = api_client.QueryParameter(
    name="type",
    style=api_client.ParameterStyle.FORM,
    schema=TypeSchema,
    required=True,
    explode=True,
)
request_query_metric = api_client.QueryParameter(
    name="metric",
    style=api_client.ParameterStyle.FORM,
    schema=MetricSchema,
    explode=True,
)
request_query_connector_ids = api_client.QueryParameter(
    name="connector_ids",
    style=api_client.ParameterStyle.FORM,
    schema=ConnectorIdsSchema,
    explode=True,
)
request_query_time_period = api_client.QueryParameter(
    name="time_period",
    style=api_client.ParameterStyle.FORM,
    schema=TimePeriodSchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = ReportsGetDataBasedOnTypeResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: ReportsGetDataBasedOnTypeResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: ReportsGetDataBasedOnTypeResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_data_based_on_type_mapped_args(
        self,
        type: str,
        metric: typing.Optional[str] = None,
        connector_ids: typing.Optional[typing.List[int]] = None,
        time_period: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if type is not None:
            _query_params["type"] = type
        if metric is not None:
            _query_params["metric"] = metric
        if connector_ids is not None:
            _query_params["connector_ids"] = connector_ids
        if time_period is not None:
            _query_params["time_period"] = time_period
        args.query = _query_params
        return args

    async def _aget_data_based_on_type_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get report data based on given type
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_type,
            request_query_metric,
            request_query_connector_ids,
            request_query_time_period,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/v1/reports',
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_data_based_on_type_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get report data based on given type
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_type,
            request_query_metric,
            request_query_connector_ids,
            request_query_time_period,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/api/v1/reports',
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetDataBasedOnTypeRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_data_based_on_type(
        self,
        type: str,
        metric: typing.Optional[str] = None,
        connector_ids: typing.Optional[typing.List[int]] = None,
        time_period: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_data_based_on_type_mapped_args(
            type=type,
            metric=metric,
            connector_ids=connector_ids,
            time_period=time_period,
        )
        return await self._aget_data_based_on_type_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get_data_based_on_type(
        self,
        type: str,
        metric: typing.Optional[str] = None,
        connector_ids: typing.Optional[typing.List[int]] = None,
        time_period: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_data_based_on_type_mapped_args(
            type=type,
            metric=metric,
            connector_ids=connector_ids,
            time_period=time_period,
        )
        return self._get_data_based_on_type_oapg(
            query_params=args.query,
        )

class GetDataBasedOnType(BaseApi):

    async def aget_data_based_on_type(
        self,
        type: str,
        metric: typing.Optional[str] = None,
        connector_ids: typing.Optional[typing.List[int]] = None,
        time_period: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> ReportsGetDataBasedOnTypeResponsePydantic:
        raw_response = await self.raw.aget_data_based_on_type(
            type=type,
            metric=metric,
            connector_ids=connector_ids,
            time_period=time_period,
            **kwargs,
        )
        if validate:
            return ReportsGetDataBasedOnTypeResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(ReportsGetDataBasedOnTypeResponsePydantic, raw_response.body)
    
    
    def get_data_based_on_type(
        self,
        type: str,
        metric: typing.Optional[str] = None,
        connector_ids: typing.Optional[typing.List[int]] = None,
        time_period: typing.Optional[str] = None,
        validate: bool = False,
    ) -> ReportsGetDataBasedOnTypeResponsePydantic:
        raw_response = self.raw.get_data_based_on_type(
            type=type,
            metric=metric,
            connector_ids=connector_ids,
            time_period=time_period,
        )
        if validate:
            return ReportsGetDataBasedOnTypeResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(ReportsGetDataBasedOnTypeResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        type: str,
        metric: typing.Optional[str] = None,
        connector_ids: typing.Optional[typing.List[int]] = None,
        time_period: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_data_based_on_type_mapped_args(
            type=type,
            metric=metric,
            connector_ids=connector_ids,
            time_period=time_period,
        )
        return await self._aget_data_based_on_type_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        type: str,
        metric: typing.Optional[str] = None,
        connector_ids: typing.Optional[typing.List[int]] = None,
        time_period: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_data_based_on_type_mapped_args(
            type=type,
            metric=metric,
            connector_ids=connector_ids,
            time_period=time_period,
        )
        return self._get_data_based_on_type_oapg(
            query_params=args.query,
        )

